<script setup lang="ts">
import { computed } from 'vue';

import gallery from '@/utils/gallery.json';

type GalleryItem = {
  url: string;
  aspectRatio: string;
  prompt: string;
};

const PROMPT_CAPTION_MAX = 90;

function pickShowcaseImage(items: GalleryItem[]): GalleryItem {
  const landscape = items.filter((item) => {
    const [w, h] = item.aspectRatio.split(':').map(Number);
    return Number.isFinite(w) && Number.isFinite(h) && w >= h;
  });
  const pool = landscape.length > 0 ? landscape : items;
  return pool[Math.floor(Math.random() * pool.length)]!;
}

const image = pickShowcaseImage(gallery as GalleryItem[]);

const caption = computed(() => {
  const prompt = image.prompt?.trim() ?? '';
  if (!prompt) return '';
  if (prompt.length <= PROMPT_CAPTION_MAX) return prompt;
  return `${prompt.slice(0, PROMPT_CAPTION_MAX - 1).trimEnd()}…`;
});

const altText = computed(() =>
  image.prompt
    ? `AI-generated artwork: ${image.prompt.slice(0, 120)}`
    : 'AI-generated artwork by Visual AI',
);
</script>

<template>
  <div class="auth">
    <aside class="auth__stage">
      <img
        class="auth__image"
        :src="image.url"
        :alt="altText"
        width="1600"
        height="900"
        decoding="async"
        fetchpriority="high"
      />
      <div class="auth__veil" aria-hidden="true" />
      <div class="auth__credit">
        <p class="auth__credit-label">Generated by Visual AI</p>
        <p v-if="caption" class="auth__credit-prompt">{{ caption }}</p>
      </div>
    </aside>

    <section class="auth__panel">
      <header class="auth__header">
        <router-link to="/" class="auth__brand" aria-label="Visual AI home">
          Visual<span class="auth__brand-accent">AI</span>
        </router-link>
      </header>

      <div class="auth__form">
        <slot />
      </div>

      <footer class="auth__footer">
        <router-link to="/" class="auth__home">Back to home</router-link>
      </footer>
    </section>
  </div>
</template>

<style scoped lang="scss">
.auth {
  /* Auth stays dark-editorial regardless of app theme — photos need the warm canvas. */
  --tw-canvas: 13 10 7;
  --tw-surface-1: 15 12 9;
  --tw-ink-primary: 240 232 220;
  --tw-ink-muted: 172 156 140;
  --tw-hairline: 58 47 36;

  min-height: 100dvh;
  display: grid;
  grid-template-areas:
    'panel'
    'stage';
  grid-template-rows: 1fr minmax(28vh, 34vh);
  background: rgb(var(--tw-canvas));
  color: rgb(var(--tw-ink-primary));
}

.auth__stage {
  grid-area: stage;
  position: relative;
  overflow: hidden;
  min-height: 28vh;
  background: rgb(var(--tw-surface-1));
}

.auth__image {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: center;
}

.auth__veil {
  position: absolute;
  inset: 0;
  background: linear-gradient(
    180deg,
    rgb(var(--tw-canvas) / 0.15) 0%,
    rgb(var(--tw-canvas) / 0.55) 55%,
    rgb(var(--tw-canvas) / 0.92) 100%
  );
  pointer-events: none;
}

.auth__credit {
  position: absolute;
  left: 1.25rem;
  right: 1.25rem;
  bottom: 1.25rem;
  z-index: 1;
  max-width: 36rem;
}

.auth__credit-label {
  margin: 0;
  font-size: 0.72rem;
  font-weight: 600;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: #d29467;
}

.auth__credit-prompt {
  margin: 0.4rem 0 0;
  font-family: 'Young Serif', Georgia, serif;
  font-size: clamp(0.95rem, 2.2vw, 1.15rem);
  line-height: 1.35;
  color: rgb(var(--tw-ink-primary) / 0.92);
  text-wrap: pretty;
}

.auth__panel {
  grid-area: panel;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: 1.5rem;
  padding: max(1.25rem, env(safe-area-inset-top)) max(1.25rem, env(safe-area-inset-right))
    max(1.25rem, env(safe-area-inset-bottom)) max(1.25rem, env(safe-area-inset-left));
  background:
    radial-gradient(circle at 50% 0%, rgba(201, 168, 76, 0.1), transparent 55%),
    rgb(var(--tw-canvas));
  border-top: 1px solid rgb(var(--tw-hairline) / 0.65);
}

.auth__header {
  display: flex;
  align-items: center;
  min-height: 2.75rem;
}

.auth__brand {
  font-family: 'Young Serif', Georgia, serif;
  font-size: 1.35rem;
  color: rgb(var(--tw-ink-primary));
  text-decoration: none;
  letter-spacing: -0.01em;
  transition: color 0.2s ease;

  &:hover {
    color: rgb(var(--tw-ink-primary));
  }

  &:focus-visible {
    outline: 2px solid #c98a5a;
    outline-offset: 4px;
    border-radius: 2px;
  }
}

.auth__brand-accent {
  color: #c98a5a;
  margin-left: 0.15em;
}

.auth__form {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  animation: auth-form-enter 0.45s cubic-bezier(0.22, 1, 0.36, 1) both;
}

.auth__footer {
  display: flex;
  justify-content: center;
  min-height: 2.75rem;
  align-items: center;
}

.auth__home {
  font-size: 0.9rem;
  color: rgb(var(--tw-ink-muted));
  text-decoration: none;
  padding: 0.65rem 0.75rem;
  border-radius: 0.375rem;
  transition: color 0.2s ease;

  &:hover {
    color: #c98a5a;
  }

  &:focus-visible {
    outline: 2px solid #c98a5a;
    outline-offset: 2px;
  }
}

@keyframes auth-form-enter {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (min-width: 900px) {
  .auth {
    grid-template-areas: 'stage panel';
    grid-template-columns: minmax(0, 1.35fr) minmax(380px, 440px);
    grid-template-rows: 1fr;
  }

  .auth__stage {
    min-height: 100dvh;
  }

  .auth__veil {
    background: linear-gradient(
      90deg,
      transparent 55%,
      rgb(var(--tw-canvas) / 0.35) 82%,
      rgb(var(--tw-canvas) / 0.85) 100%
    );
  }

  .auth__credit {
    left: 1.75rem;
    right: auto;
    bottom: 1.75rem;
    max-width: 28rem;
  }

  .auth__panel {
    border-top: none;
    border-left: 1px solid rgb(var(--tw-hairline) / 0.65);
    padding: 2rem 1.75rem;
  }
}

@media (prefers-reduced-motion: reduce) {
  .auth__form {
    animation: none;
  }
}
</style>
