import { mount } from '@vue/test-utils';
import { describe, expect, it } from 'vitest';

import AuthShell from '@/components/Auth/AuthShell.vue';

describe('AuthShell', () => {
  it('renders the showcase stage, brand, and slot', () => {
    const wrapper = mount(AuthShell, {
      slots: { default: '<form class="signin-slot">Sign in</form>' },
      global: {
        stubs: {
          RouterLink: {
            props: ['to'],
            template: "<a :href=\"typeof to === 'string' ? to : '/'\"><slot /></a>",
          },
        },
      },
    });

    expect(wrapper.find('.auth__image').exists()).toBe(true);
    expect(wrapper.text()).toContain('Generated by Visual AI');
    expect(wrapper.text()).toContain('Back to home');
    expect(wrapper.find('.signin-slot').exists()).toBe(true);
  });
});
