name: Deploy Backend

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
                  chmod 600 ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa.pub
                  ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

            - name: Build and Deploy Docker Image
              run: |
                  ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << EOF
                  # Ensure Docker is installed
                  if ! [ -x "$(command -v docker)" ]; then
                    apt-get update
                    apt-get install -y docker.io
                  fi

                  # Pull latest changes from GitHub
                  cd /root/visual-ai/backend/visual-ai-backend || exit
                  git pull

                  # Build and run the updated Docker container
                  docker compose --env-file .env.production up -d --build
                  EOF
