<script setup>
import { SignUp } from 'vue-clerk'
</script>

<template>
  <div class="tw-flex tw-flex-col md:tw-flex-row">
    <!-- Image column -->
    <div class="tw-relative tw-w-full md:tw-w-[70%] tw-h-screen">
      <img
        src="../assets/about.jpg"
        alt="AI Generated Image"
        class="tw-object-cover tw-w-full tw-h-full"
      />
      <div class="tw-absolute tw-inset-0 tw-bg-black tw-opacity-20 md:tw-opacity-0"></div>
      <p
        class="tw-absolute tw-bottom-4 tw-font-bold tw-left-4 tw-text-white tw-text-sm md:tw-text-base"
      >
        Image generated by Visual AI
      </p>
    </div>

    <!-- SignUp column -->

    <div
      class="tw-absolute md:tw-relative tw-inset-0 md:tw-w-[30%] tw-flex tw-items-center tw-justify-center bg-gradient"
    >
      <SignUp path="/signup" />
    </div>
  </div>
</template>

<style scoped lang="scss">
.bg-gradient {
  background: radial-gradient(circle at 50% 50%, #261f2a, #251531, #2f032f, #2e0854);
  background-size: 200% 200%;
  animation: moveGradient 20s ease infinite;

  &::before {
    content: '';
    background: radial-gradient(circle at 50% 50%, #261f2a, #251531, #2f032f, #2e0854);
    background-size: 200% 200%;
    animation: moveGradient 20s ease infinite;
  }
}

@keyframes moveGradient {
  0%,
  100% {
    background-position: 0% 0%;
  }
  25% {
    background-position: 100% 0%;
  }
  50% {
    background-position: 100% 100%;
  }
  75% {
    background-position: 0% 100%;
  }
}
</style>
