server {
    listen 80;
    server_name www.visual-ai.app visual-ai.app;
    return 301 https://$host$request_uri;

    # Write Access and Error logs
    access_log        /var/log/nginx/.access.log;
    error_log         /var/log/nginx/error.log;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}
server {
    listen 443 ssl;
    server_name *.visual-ai.app visual-ai.app;

    ssl_certificate /etc/letsencrypt/live/visual-ai.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/visual-ai.app/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}