/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    AIImageAside: typeof import('./components/Aside/AIImageAside.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Aside: typeof import('./components/Aside/Aside.vue')['default']
    Coin: typeof import('./components/Coin.vue')['default']
    ColorizeImageAside: typeof import('./components/Aside/ColorizeImageAside.vue')['default']
    Credits: typeof import('./components/Credits.vue')['default']
    FAQ: typeof import('./components/FAQ.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    IconCamera: typeof import('./components/icons/IconCamera.vue')['default']
    IconCameraDark: typeof import('./components/icons/IconCameraDark.vue')['default']
    IconCoin: typeof import('./components/icons/IconCoin.vue')['default']
    IconColorize: typeof import('./components/icons/IconColorize.vue')['default']
    IconDropper: typeof import('./components/icons/IconDropper.vue')['default']
    IconDropperDark: typeof import('./components/icons/IconDropperDark.vue')['default']
    IconExpand: typeof import('./components/icons/IconExpand.vue')['default']
    IconExpandDark: typeof import('./components/icons/IconExpandDark.vue')['default']
    IconImage: typeof import('./components/icons/IconImage.vue')['default']
    IconImageFrame: typeof import('./components/icons/IconImageFrame.vue')['default']
    IconImageFrameDark: typeof import('./components/icons/IconImageFrameDark.vue')['default']
    IconOld: typeof import('./components/icons/IconOld.vue')['default']
    IconPremium: typeof import('./components/icons/IconPremium.vue')['default']
    IconStar: typeof import('./components/icons/IconStar.vue')['default']
    IconUpscale: typeof import('./components/icons/IconUpscale.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    Pricing: typeof import('./components/Pricing.vue')['default']
    PricingCard: typeof import('./components/PricingCard.vue')['default']
    PricingDialog: typeof import('./components/PricingDialog.vue')['default']
    ResultColumn: typeof import('./components/ResultColumn.vue')['default']
    ReviveOldAside: typeof import('./components/Aside/ReviveOldAside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeButton: typeof import('./components/ThemeButton.vue')['default']
    UpscaleIconComponent: typeof import('./components/icons/UpscaleIconComponent.vue')['default']
    UpscaleImageAside: typeof import('./components/Aside/UpscaleImageAside.vue')['default']
  }
}
