/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/FAQs': RouteRecordInfo<'/FAQs', '/FAQs', Record<never, never>, Record<never, never>>,
    'privacy': RouteRecordInfo<'privacy', '/PrivacyPolicy', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/Profile', Record<never, never>, Record<never, never>>,
    'refund': RouteRecordInfo<'refund', '/Refund', Record<never, never>, Record<never, never>>,
    'signin': RouteRecordInfo<'signin', '/Signin', Record<never, never>, Record<never, never>>,
    '/Signup': RouteRecordInfo<'/Signup', '/Signup', Record<never, never>, Record<never, never>>,
    'terms': RouteRecordInfo<'terms', '/Terms', Record<never, never>, Record<never, never>>,
  }
}
