export const MODEL_IDS = {
  FLUX_QUICK: "FLUX_QUICK",
  FLUX_BASIC: "FLUX_BASIC",
  FLUX_PRO: "FLUX_PRO",
  FLUX_1_1_PRO: "FLUX_1_1_PRO",
  FLUX_REALISM: "FLUX_REALISM",
  UPSCALE_IMAGE: "UPSCALE_IMAGE",
  COLORIZE_BASIC: "COLORIZE_BASIC",
  COLORIZE_ADVANCED: "COLORIZE_ADVANCED",
  REVIVE: "REVIVE",
  REMOVE_BACKGROUND: "REMOVE_BACKGROUND",
} as const;

export type ModelId = (typeof MODEL_IDS)[keyof typeof MODEL_IDS];
