/**
 * Upscaler showcase image mappings
 *
 * Auto-generated by scripts/generate-upscaler-showcase.ts
 * DO NOT EDIT by hand
 */

export const UPSCALER_SHOWCASE = [
  {
    modelKey: 'UPSCALE_REAL_ESRGAN',
    source: '/showcase/upscalers/source/real-esrgan-source.jpg',
    upscaled: '/showcase/upscalers/upscaled/upscale_real_esrgan-upscaled.jpg',
  },

  {
    modelKey: 'UPSCALE_PRUNA',
    source: '/showcase/upscalers/source/pruna-source.jpg',
    upscaled: '/showcase/upscalers/upscaled/upscale_pruna-upscaled.jpg',
  },

  {
    modelKey: 'UPSCALE_RECRAFT',
    source: '/showcase/upscalers/source/recraft-source.jpg',
    upscaled: '/showcase/upscalers/upscaled/upscale_recraft-upscaled.jpg',
  },

  {
    modelKey: 'UPSCALE_CLARITY_PRO',
    source: '/showcase/upscalers/source/clarity-pro-source.jpg',
    upscaled: '/showcase/upscalers/upscaled/upscale_clarity_pro-upscaled.jpg',
  },

  {
    modelKey: 'UPSCALE_TOPAZ',
    source: '/showcase/upscalers/source/topaz-source.jpg',
    upscaled: '/showcase/upscalers/upscaled/upscale_topaz-upscaled.jpg',
  },
] as const;

export type UpscalerShowcaseEntry = (typeof UPSCALER_SHOWCASE)[number];

export function getShowcaseEntry(modelKey: string): UpscalerShowcaseEntry | undefined {
  return UPSCALER_SHOWCASE.find((e) => e.modelKey === modelKey);
}
