services:
    backend:
        container_name: backend
        restart: always
        build:
            context: . # Refers to the current directory (backend directory)
            dockerfile: Dockerfile # Refers to the Dockerfile in the current directory
        ports:
            - "${APP_PORT}:${APP_PORT}"
        environment:
            APP_SERVER: ${APP_SERVER}
            APP_PORT: ${APP_PORT}
            NODE_ENV: ${NODE_ENV}
            REPLICATE_API_TOKEN: ${REPLICATE_API_TOKEN}
            MONGO_URI: ${MONGO_URI}
            MONGO_DB_USER: ${MONGO_DB_USER}
            MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
            WEBHOOK_SECRET: ${WEBHOOK_SECRET}
            CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
            CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
            CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
            CLOUDINARY_BASE_PATH: ${CLOUDINARY_BASE_PATH}
            CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
            CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
            CLERK_JWT_KEY: ${CLERK_JWT_KEY}
            RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
            RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
            EMAIL_USER: ${EMAIL_USER}
            EMAIL_PASSWORD: ${EMAIL_PASSWORD}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
        depends_on:
            - redis

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: redis-server --appendonly yes --appendfsync everysec --save 60 1 --loglevel warning --maxmemory 128mb --maxmemory-policy allkeys-lru
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

volumes:
    redis_data:
