name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
      # - name: Install SSH Key
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and Deploy Docker Image
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << EOF
          # Ensure Docker is installed
          if ! [ -x "$(command -v docker)" ]; then
            apt-get update
            apt-get install -y docker.io
          fi

          # Pull latest changes from GitHub
          cd /root/visual-ai/frontend/visual-ai || exit
          git pull

          # Build and run the updated Docker container
          docker build -t vue-app .
          docker stop vue-app || true
          docker rm vue-app || true
          docker run -d -p 8080:80 --name vue-app vue-app
          EOF
