name: Deploy Vue App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh root@159.89.45.226 << 'EOF'
          # Navigate to the app directory
          cd ~/visual-ai/frontend/visual-ai

          # Pull latest changes and build
          git pull
          yarn install
          npm run build

          # Copy build files to Nginx directory
          sudo cp -r dist/* /var/www/html/visual-ai

          # Restart Nginx
          sudo systemctl restart nginx
          EOF
